# Generated by Django 5.0.6 on 2024-05-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_stock_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="stocks",
            field=models.ManyToManyField(
                default=[], related_name="watchlists", to="api.stock"
            ),
        ),
    ]
