# Generated by Django 5.0.6 on 2024-05-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_watchlist_name_alter_watchlist_stocks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="stocks",
            field=models.ManyToManyField(related_name="watchlists", to="api.stock"),
        ),
    ]
