# Generated by Django 5.0.6 on 2024-05-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_watchlist_stocks"),
    ]

    operations = [
        migrations.DeleteModel(name="Note",),
    ]
